
#management:
#    security:
#        enabled: false # disable security for actuators (only for non-prod env)

spring:
    data:
        rest:
            basePath: /api
            returnBodyOnCreate: true
            returnBodyOnUpdate: true
            maxPageSize: 1000
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
    datasource:
        sqlScriptEncoding: UTF-8


# Configuration tokens
team:
    validation:
        name:
            maxWords: 1
        favorites:
            max: 5